name: aibibite
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^6.1.0
  supabase_flutter: ^2.5.7
  image_picker: ^1.0.7
  google_mlkit_barcode_scanning: ^0.10.0
  google_mlkit_commons: ^0.6.1
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  fl_chart: ^0.68.0
  intl: ^0.19.0
  url_launcher: ^6.2.5
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - lib/assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "lib/assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "lib/assets/images/logo.png"
  android: true
  ios: true
  image_dark: "lib/assets/images/logo.png"
  color_dark: "#FFFFFF"
  android_gravity: center
  ios_content_mode: scaleAspectFit
